
require "mbox-dev/version"
require "cocoapods"
require "mbox-cocoapods"
require "mbox-dev/config.rb"
require "mbox-dev/analyzer.rb"
require "mbox-dev/podfile.rb"
require "mbox-dev/resolver.rb"
require "mbox-dev/user_project_integrator.rb"
require "mbox-dev/aggregate_target.rb"
require "mbox-dev/target_integrator.rb"
require "mbox-dev/embed_frameworks_script.rb"
require "mbox-dev/remove_dependencies.rb"
require "mbox-dev/inject_framework_search_paths.rb"
